Bump actionlint from 1.7.4 to 1.7.5 (#21)

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -20,7 +20,7 @@ defaults:
 
 jobs:
   get-versions:
-    name: Get 5 latest versions
+    name: Get 3 latest versions
     runs-on: ubuntu-latest
     timeout-minutes: 10
     outputs:
@@ -28,26 +28,105 @@ jobs:
     steps:
       - name: Prepare list
         id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
+          TARGET_REPO: "ciao-lang/ciao"
         run: |
-          url="https://api.github.com/repos/ciao-lang/ciao/releases"
-          versions=$(curl -s "${url}" | jq -c '[.[0:5][].tag_name] | map(sub("^v"; ""))')
+          versions=$(curl -sL \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${TARGET_REPO}/releases" \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '[.[0:($n | tonumber)][].tag_name] | map(sub("^v"; "")) | . += ["latest"]')
           echo "versions=${versions}" >> "$GITHUB_OUTPUT"
   setup-ciao:
     name: Setup Ciao
     needs: [get-versions]
-    timeout-minutes: 10
+    runs-on: ${{ matrix.os }}-latest
+    timeout-minutes: 5
     strategy:
       fail-fast: false
       matrix:
         os: ["ubuntu", "macos"]
         version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
-    runs-on: ${{ matrix.os }}-latest
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
       - name: Setup Ciao
+        id: setup-ciao
         uses: ./
         with:
           version: ${{ matrix.version }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong completion status" \
+            "${{ steps.setup-ciao.outcome }}" \
+            "success"
+          test_equal "ciao should not be installed" \
+            "${{ steps.setup-ciao.outputs.installed }}" \
+            "true"
       - name: Run command
         run: ciao list
+  windows-not-supported:
+    name: Windows not supported
+    runs-on: windows-latest
+    timeout-minutes: 5
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup Ciao
+        id: setup-ciao
+        continue-on-error: true
+        uses: ./
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong completion status" \
+            "${{ steps.setup-ciao.outcome }}" \
+            "failure"
+          test_equal "ciao should not be installed" \
+            "${{ steps.setup-ciao.outputs.installed }}" \
+            "false"
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup Ciao 1
+        id: setup-ciao-1
+        uses: ./
+      - name: Setup Ciao 2
+        id: setup-ciao-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-ciao-1" \
+            "${{ steps.setup-ciao-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-ciao-2" \
+            "${{ steps.setup-ciao-2.outputs.installed }}" \
+            "${{ matrix.force }}"
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,37 +7,59 @@ branding:
   color: gray-dark
 inputs:
   version:
-    description: "Ciao version."
+    description: Ciao version. Defaults to the latest version.
     required: false
-    default: "1.24.0-m1"
+    default: "latest"
+  force:
+    description: |
+      If "false" skips installation if ciao is already installed. If "true"
+      installs ciao in any case. Defaults to "false".
+    required: false
+    default: "false"
+outputs:
+  installed:
+    description: Whether ciao was installed or not.
+    value: "${{ steps.install-ciao.outcome == 'success' }}"
 runs:
   using: "composite"
   steps:
     - name: Fail
       if: ${{ runner.os == 'Windows' }}
-      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
     - name: Collect info
       id: info
+      env:
+        INPUT_FORCE: "${{ inputs.force }}"
       run: |
-        ciao_installed=$(if command -v ciao >/dev/null 2>&1; then echo true; else echo false; fi)
-        echo "ciao-installed=${ciao_installed}" >> "$GITHUB_OUTPUT"
-        bin_path="${GITHUB_WORKSPACE}/ciao"
-        mkdir -p "${bin_path}"
-        echo "ciao-path=${bin_path}" >> "$GITHUB_OUTPUT"
+        if [ "${INPUT_FORCE}" = "false" ] && command -v ciao >/dev/null 2>&1; then
+          bin_installed="true"
+        else
+          bin_installed="false"
+        fi
+        echo "bin-installed=${bin_installed}" >> "$GITHUB_OUTPUT"
+
+        bin_dir="ciao_$(date +%s)"
+        echo "bin-dir=${bin_dir}" >> "$GITHUB_OUTPUT"
+
+        bin_path="$GITHUB_WORKSPACE/${bin_dir}"
+        echo "bin-path=${bin_path}" >> "$GITHUB_OUTPUT"
       shell: sh
     - name: Download Ciao
-      if: ${{ steps.info.outputs.ciao-installed == 'false' }}
+      if: ${{ steps.info.outputs.bin-installed == 'false' }}
       uses: actions/checkout@v4
       with:
-        repository: ciao-lang/ciao
-        ref: v${{ inputs.version }}
+        repository: "ciao-lang/ciao"
+        ref: ${{ inputs.version == 'latest' && 'master' || format('v{0}', inputs.version) }}
         fetch-depth: 1
-        path: ciao
+        path: ${{ steps.info.outputs.bin-dir }}
     - name: Install Ciao
-      if: ${{ steps.info.outputs.ciao-installed == 'false' }}
+      if: ${{ steps.info.outputs.bin-installed == 'false' }}
+      id: install-ciao
       run: |
         ./ciao-boot.sh local-install
-        echo "${{ steps.info.outputs.ciao-path }}/build/bin" >> "$GITHUB_PATH"
+        echo "$(pwd)/build/bin" >> "$GITHUB_PATH"
       shell: sh
-      working-directory: ${{ steps.info.outputs.ciao-path }}
+      working-directory: "${{ steps.info.outputs.bin-path }}"
