Fix tests 36

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -46,7 +46,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: ["ubuntu", "macos", "windows"]
+        os: ["ubuntu", "macos"]
         version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
     steps:
       - name: Checkout ${{ github.repository }}
@@ -72,6 +72,31 @@ jobs:
             "true"
       - name: Run command
         run: ciao list
+  windows-not-supported:
+    name: Windows not supported
+    runs-on: windows-latest
+    timeout-minutes: 5
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup Ciao
+        id: setup-ciao
+        continue-on-error: true
+        uses: ./
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong completion status" \
+            "${{ steps.setup-ciao.outcome }}" \
+            "failure"
+          test_equal "ciao should not be installed" \
+            "${{ steps.setup-ciao.outputs.installed }}" \
+            "false"
   test-force:
     name: Test force
     runs-on: ubuntu-latest
